### ISSUE TITLE
from visa import instrument - does not work

### ISSUE THREAD

**Issue by rudi48** [baldwint/wanglib#2]
Hello,
I have installed pyVisa version 1.8 under Python 2.7.
When I try to import, I get:

``` python
>>> from visa import instrument
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name instrument
>>> import visa
>>> dir (visa)
['Error', 'InvalidBinaryFormat', 'InvalidSession', 'LibraryError', 'OSNotSupported', 'Resource', 'ResourceManager', 'UnknownHandler', 'VisaIOError', 'VisaIOWarning', 'VisaTypeError', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__version__', 'absolute_import', 'constants', 'division', 'log_to_screen', 'logger', 'print_function', 'unicode_literals']
```

I have found the solution on link:
https://pyvisa.readthedocs.org/en/stable/migrating.html?highlight=instrument
But when I try further:

``` python
>>> rm = visa.ResourceManager()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/PyVISA-1.8-py2.7.egg/pyvisa/highlevel.py", line 1488, in __new__
    visa_library = open_visa_library(visa_library)
  File "/Library/Python/2.7/site-packages/PyVISA-1.8-py2.7.egg/pyvisa/highlevel.py", line 1460, in open_visa_library
    return cls(argument)
  File "/Library/Python/2.7/site-packages/PyVISA-1.8-py2.7.egg/pyvisa/highlevel.py", line 96, in __new__
    raise OSError('Could not open VISA library:\n' + '\n'.join(errs))
OSError: Could not open VISA library:
```

What can I do to solve the problem?

Regards, Rudolf

**Comment by baldwint** [comment]
Is NI-VISA installed on the machine? This software (from National Instruments) is that which actually controls instruments connected via (for example) a NI-branded GPIB card. PyVISA only provides the interface to Python.

If your instrument is connected via a Prologix controller, you do not need PyVISA at all. In that case supply a `wanglib.prologix.instrument` instance to the instrument class you want to use in place of a `visa.instrument` instance.

**Comment by rudi48** [comment]
Hello Thomas,
Thank you very much for your help. I started this issue at the beginning of my evaluation of Wanglib.
Unfortunately I do not know the National Instruments NI-VISA package.
Now I have more knowledge, and I hope I can help myself.
Regards, Rudolf
